import type { Program, Coach, CalendarEvent, ContactLogEntry, TimelineEvent } from './types';

// Demo data — will be replaced by live Google Sheets data once OAuth is configured

export const DEMO_LACROSSE_PROGRAMS: Program[] = [
  // ===== TOP 25 D1 PROGRAMS (2026 IWLCA Coaches Poll, March 23 2026) =====
  // #1 North Carolina
  {
    _rowIndex: 2, School: 'North Carolina', Division: 'D1', Conference: 'ACC',
    'Academic Ranking': '#22', 'Acceptance Rate': '17%',
    'Head Coach': 'Jenny Levy', 'Coach Email': 'wlax@unc.edu',
    'Coach Phone': '', 'Coach Background': 'Led UNC to 3 NCAA titles; one of the winningest coaches in D1 history',
    'Choate Connection': '', 'Roster Size': '34', 'Goalies on Roster': '3',
    'Graduating Goalies': '0', 'Program URL': 'https://goheels.com/sports/womens-lacrosse',
    'Questionnaire URL': '', Priority: '', Notes: 'Chapel Hill, NC', 'Last Updated': '2026-03-29',
  },
  // #2 Stanford
  {
    _rowIndex: 3, School: 'Stanford', Division: 'D1', Conference: 'ACC',
    'Academic Ranking': '#3', 'Acceptance Rate': '4%',
    'Head Coach': 'Danielle Spencer', 'Coach Email': '',
    'Coach Phone': '', 'Coach Background': 'Northwestern alum (2010), 3x NCAA champion as player; swept Pac-12 titles in 2021, 2022, 2024',
    'Choate Connection': '', 'Roster Size': '33', 'Goalies on Roster': '',
    'Graduating Goalies': '', 'Program URL': 'https://gostanford.com/sports/womens-lacrosse',
    'Questionnaire URL': '', Priority: '', Notes: 'Stanford, CA', 'Last Updated': '2026-03-29',
  },
  // #3 Maryland
  {
    _rowIndex: 4, School: 'Maryland', Division: 'D1', Conference: 'Big Ten',
    'Academic Ranking': '#46', 'Acceptance Rate': '45%',
    'Head Coach': 'Cathy Reese', 'Coach Email': '',
    'Coach Phone': '', 'Coach Background': 'Maryland alum (1998), 5x NCAA champion coach, 2025 IWLCA Hall of Fame inductee, 350+ career wins',
    'Choate Connection': '', 'Roster Size': '35', 'Goalies on Roster': '',
    'Graduating Goalies': '', 'Program URL': 'https://umterps.com/sports/womens-lacrosse',
    'Questionnaire URL': '', Priority: '', Notes: 'College Park, MD', 'Last Updated': '2026-03-29',
  },
  // #4 Navy
  {
    _rowIndex: 5, School: 'Navy', Division: 'D1', Conference: 'Patriot League',
    'Academic Ranking': '##15 LAC (service academy)', 'Acceptance Rate': '8%',
    'Head Coach': 'Cindy Timchal', 'Coach Email': '',
    'Coach Phone': '', 'Coach Background': 'West Chester alum, NCAA all-time wins leader (600+), 8x NCAA champion at Maryland before building Navy program',
    'Choate Connection': '', 'Roster Size': '32', 'Goalies on Roster': '',
    'Graduating Goalies': '', 'Program URL': 'https://navysports.com/sports/womens-lacrosse',
    'Questionnaire URL': '', Priority: '', Notes: 'Annapolis, MD. Service academy commitment required.', 'Last Updated': '2026-03-29',
  },
  // #5 Syracuse
  {
    _rowIndex: 6, School: 'Syracuse', Division: 'D1', Conference: 'ACC',
    'Academic Ranking': '#62', 'Acceptance Rate': '44%',
    'Head Coach': 'Regy Thorpe', 'Coach Email': 'rjthorpe@syr.edu',
    'Coach Phone': '', 'Coach Background': 'Syracuse alum, NCAA champion as player (1993), 10 yrs as SU assistant, came from Florida as associate HC',
    'Choate Connection': '', 'Roster Size': '32', 'Goalies on Roster': '2',
    'Graduating Goalies': '1 (2027)', 'Program URL': 'https://cuse.com/sports/womens-lacrosse',
    'Questionnaire URL': '', Priority: '', Notes: 'Syracuse, NY', 'Last Updated': '2026-03-29',
  },
  // #6 Johns Hopkins
  {
    _rowIndex: 7, School: 'Johns Hopkins', Division: 'D1', Conference: 'Big Ten',
    'Academic Ranking': '#9', 'Acceptance Rate': '6%',
    'Head Coach': 'Tim McCormack', 'Coach Email': '',
    'Coach Phone': '', 'Coach Background': 'UMass alum (2012), former Northwestern assistant and Arizona State HC; 4th year at JHU',
    'Choate Connection': '', 'Roster Size': '32', 'Goalies on Roster': '',
    'Graduating Goalies': '', 'Program URL': 'https://hopkinssports.com/sports/womens-lacrosse',
    'Questionnaire URL': '', Priority: '', Notes: 'Baltimore, MD. Elite academics + lacrosse hotbed.', 'Last Updated': '2026-03-29',
  },
  // #7 Florida
  {
    _rowIndex: 8, School: 'Florida', Division: 'D1', Conference: 'SEC',
    'Academic Ranking': '#28', 'Acceptance Rate': '23%',
    'Head Coach': 'Amanda O\'Leary', 'Coach Email': '',
    'Coach Phone': '', 'Coach Background': 'Temple alum (1988), NCAA champion as player, US Lacrosse Hall of Fame, 2026 IWLCA Hall of Fame inductee',
    'Choate Connection': '', 'Roster Size': '34', 'Goalies on Roster': '',
    'Graduating Goalies': '', 'Program URL': 'https://floridagators.com/sports/womens-lacrosse',
    'Questionnaire URL': '', Priority: '', Notes: 'Gainesville, FL', 'Last Updated': '2026-03-29',
  },
  // #8 Yale
  {
    _rowIndex: 9, School: 'Yale', Division: 'D1', Conference: 'Ivy League',
    'Academic Ranking': '#5', 'Acceptance Rate': '5%',
    'Head Coach': 'Erica Bamford', 'Coach Email': 'erica.bamford@yale.edu',
    'Coach Phone': '', 'Coach Background': 'Joel E. Smilow \'54 Head Coach. Former US National Team. 2024 Ivy League Coach of the Year.',
    'Choate Connection': 'Strong Choate-Yale pipeline', 'Roster Size': '30',
    'Goalies on Roster': '2', 'Graduating Goalies': '1 (2028)',
    'Program URL': 'https://yalebulldogs.com/sports/womens-lacrosse',
    'Questionnaire URL': '', Priority: '', Notes: 'New Haven, CT. Close proximity to Choate.',
    'Last Updated': '2026-03-29',
  },
  // #9 Michigan
  {
    _rowIndex: 10, School: 'Michigan', Division: 'D1', Conference: 'Big Ten',
    'Academic Ranking': '#21', 'Acceptance Rate': '18%',
    'Head Coach': 'Hannah Nielsen', 'Coach Email': 'wlax@umich.edu',
    'Coach Phone': '', 'Coach Background': 'Former Tewaaraton Award winner at Northwestern',
    'Choate Connection': '', 'Roster Size': '33', 'Goalies on Roster': '3',
    'Graduating Goalies': '1 (2028)', 'Program URL': 'https://mgoblue.com/sports/womens-lacrosse',
    'Questionnaire URL': '', Priority: '', Notes: 'Ann Arbor, MI. August camp on watchlist.',
    'Last Updated': '2026-03-29',
  },
  // #10 Clemson
  {
    _rowIndex: 11, School: 'Clemson', Division: 'D1', Conference: 'ACC',
    'Academic Ranking': '#77', 'Acceptance Rate': '43%',
    'Head Coach': 'Allison Kwolek', 'Coach Email': '',
    'Coach Phone': '', 'Coach Background': 'William & Mary alum, W&M Hall of Fame; formerly HC at Richmond (64-16 record); inaugural Clemson HC',
    'Choate Connection': '', 'Roster Size': '33', 'Goalies on Roster': '',
    'Graduating Goalies': '', 'Program URL': 'https://clemsontigers.com/sports/womens-lacrosse',
    'Questionnaire URL': '', Priority: '', Notes: 'Clemson, SC. New program (started 2023), rising fast.', 'Last Updated': '2026-03-29',
  },
  // #11 Stony Brook
  {
    _rowIndex: 12, School: 'Stony Brook', Division: 'D1', Conference: 'CAA',
    'Academic Ranking': '#77', 'Acceptance Rate': '49%',
    'Head Coach': 'Joe Spallina', 'Coach Email': '',
    'Coach Phone': '', 'Coach Background': 'Adelphi alum (1996), 3x D2 national champ coach at Adelphi; 224-45 at SB, 12 straight NCAA bids',
    'Choate Connection': '', 'Roster Size': '32', 'Goalies on Roster': '',
    'Graduating Goalies': '', 'Program URL': 'https://stonybrookathletics.com/sports/womens-lacrosse',
    'Questionnaire URL': '', Priority: '', Notes: 'Stony Brook, NY', 'Last Updated': '2026-03-29',
  },
  // #12 Northwestern
  {
    _rowIndex: 13, School: 'Northwestern', Division: 'D1', Conference: 'Big Ten',
    'Academic Ranking': '#9', 'Acceptance Rate': '7%',
    'Head Coach': 'Kelly Amonte Hiller', 'Coach Email': 'h-amonte@northwestern.edu',
    'Coach Phone': '', 'Coach Background': 'Maryland alum, former US National Team, 7x NCAA Champion coach',
    'Choate Connection': '', 'Roster Size': '35', 'Goalies on Roster': '3',
    'Graduating Goalies': '1 (2027)', 'Program URL': 'https://nusports.com/sports/womens-lacrosse',
    'Questionnaire URL': '', Priority: '', Notes: 'Evanston, IL', 'Last Updated': '2026-03-29',
  },
  // #13 Notre Dame
  {
    _rowIndex: 14, School: 'Notre Dame', Division: 'D1', Conference: 'ACC',
    'Academic Ranking': '#18', 'Acceptance Rate': '13%',
    'Head Coach': 'Christine Halfpenny', 'Coach Email': '',
    'Coach Phone': '', 'Coach Background': 'Virginia Tech alum, 15th season at ND; NCAA tournament in 9 of 11 completed seasons; former William & Mary HC',
    'Choate Connection': '', 'Roster Size': '33', 'Goalies on Roster': '',
    'Graduating Goalies': '', 'Program URL': 'https://fightingirish.com/sports/wlax',
    'Questionnaire URL': '', Priority: '', Notes: 'Notre Dame, IN', 'Last Updated': '2026-03-29',
  },
  // #14 Colorado
  {
    _rowIndex: 15, School: 'Colorado', Division: 'D1', Conference: 'Big 12',
    'Academic Ranking': '#105', 'Acceptance Rate': '78%',
    'Head Coach': 'Ann Elliott Whidden', 'Coach Email': '',
    'Coach Phone': '', 'Coach Background': 'Northwestern alum (2007), 3x NCAA champion as player, 3x as NU assistant; built CU program from scratch',
    'Choate Connection': '', 'Roster Size': '33', 'Goalies on Roster': '',
    'Graduating Goalies': '', 'Program URL': 'https://cubuffs.com/sports/womens-lacrosse',
    'Questionnaire URL': '', Priority: '', Notes: 'Boulder, CO', 'Last Updated': '2026-03-29',
  },
  // #15 Boston College
  {
    _rowIndex: 16, School: 'Boston College', Division: 'D1', Conference: 'ACC',
    'Academic Ranking': '#36', 'Acceptance Rate': '17%',
    'Head Coach': 'Acacia Walker-Weinstein', 'Coach Email': 'walkerau@bc.edu',
    'Coach Phone': '', 'Coach Background': 'Former Northwestern All-American, led BC to consecutive Final Fours',
    'Choate Connection': '', 'Roster Size': '33', 'Goalies on Roster': '3',
    'Graduating Goalies': '1 (2028)', 'Program URL': 'https://bceagles.com/sports/womens-lacrosse',
    'Questionnaire URL': '', Priority: '', Notes: 'Chestnut Hill, MA', 'Last Updated': '2026-03-29',
  },
  // #16 Army
  {
    _rowIndex: 17, School: 'Army', Division: 'D1', Conference: 'Patriot League',
    'Academic Ranking': '#ranked (service academy)', 'Acceptance Rate': '12%',
    'Head Coach': 'Michelle Tumolo', 'Coach Email': '',
    'Coach Phone': '', 'Coach Background': 'Syracuse alum, Tewaaraton finalist, former Oregon/Florida/Syracuse assistant; Noto Family HC at Army',
    'Choate Connection': '', 'Roster Size': '32', 'Goalies on Roster': '',
    'Graduating Goalies': '', 'Program URL': 'https://goarmywestpoint.com/sports/womens-lacrosse',
    'Questionnaire URL': '', Priority: '', Notes: 'West Point, NY. Service academy commitment required.', 'Last Updated': '2026-03-29',
  },
  // #17 Duke
  {
    _rowIndex: 18, School: 'Duke', Division: 'D1', Conference: 'ACC',
    'Academic Ranking': '#7', 'Acceptance Rate': '6%',
    'Head Coach': 'Kerstin Kimel', 'Coach Email': 'kmkimel@duke.edu',
    'Coach Phone': '', 'Coach Background': 'Maryland alum (1993), 1992 NCAA champion as player; only HC in Duke WLax history (since 1996)',
    'Choate Connection': '', 'Roster Size': '33', 'Goalies on Roster': '',
    'Graduating Goalies': '', 'Program URL': 'https://goduke.com/sports/womens-lacrosse',
    'Questionnaire URL': '', Priority: '', Notes: 'Durham, NC', 'Last Updated': '2026-03-29',
  },
  // #18 Denver
  {
    _rowIndex: 19, School: 'Denver', Division: 'D1', Conference: 'Big East',
    'Academic Ranking': '#105', 'Acceptance Rate': '58%',
    'Head Coach': 'Liza Kelly', 'Coach Email': '',
    'Coach Phone': '', 'Coach Background': 'Delaware alum, 3x All-American; 19th season at DU, 6 straight NCAA bids; formerly HC at Boston University',
    'Choate Connection': '', 'Roster Size': '33', 'Goalies on Roster': '',
    'Graduating Goalies': '', 'Program URL': 'https://denverpioneers.com/sports/womens-lacrosse',
    'Questionnaire URL': '', Priority: '', Notes: 'Denver, CO', 'Last Updated': '2026-03-29',
  },
  // #19 Princeton
  {
    _rowIndex: 20, School: 'Princeton', Division: 'D1', Conference: 'Ivy League',
    'Academic Ranking': '#1', 'Acceptance Rate': '4%',
    'Head Coach': 'Jenn Cook', 'Coach Email': 'jc30@princeton.edu',
    'Coach Phone': '', 'Coach Background': 'Promoted after Chris Sailer retired (36-yr career). 7 Ivy League titles as assistant.',
    'Choate Connection': 'Strong Choate pipeline to Ivy', 'Roster Size': '30',
    'Goalies on Roster': '3', 'Graduating Goalies': '1 (2028)',
    'Program URL': 'https://goprincetontigers.com/sports/womens-lacrosse',
    'Questionnaire URL': '', Priority: '', Notes: 'Princeton, NJ. Ivy -- no athletic scholarships but strong aid.',
    'Last Updated': '2026-03-29',
  },
  // #20 Virginia
  {
    _rowIndex: 21, School: 'Virginia', Division: 'D1', Conference: 'ACC',
    'Academic Ranking': '#24', 'Acceptance Rate': '19%',
    'Head Coach': 'Sonia LaMonica', 'Coach Email': '',
    'Coach Phone': '', 'Coach Background': 'Maryland alum (2003), 2x national champion as player; formerly 13-yr HC at Towson; Australian-born',
    'Choate Connection': '', 'Roster Size': '33', 'Goalies on Roster': '',
    'Graduating Goalies': '', 'Program URL': 'https://virginiasports.com/sports/wlax',
    'Questionnaire URL': '', Priority: '', Notes: 'Charlottesville, VA', 'Last Updated': '2026-03-29',
  },
  // #21 Loyola Maryland
  {
    _rowIndex: 22, School: 'Loyola Maryland', Division: 'D1', Conference: 'Patriot League',
    'Academic Ranking': '##4 Regional', 'Acceptance Rate': '77%',
    'Head Coach': 'Jen Adams', 'Coach Email': '',
    'Coach Phone': '', 'Coach Background': 'Maryland alum (2001), NCAA career scoring record holder, 4x national champion as player; US Lacrosse Hall of Fame',
    'Choate Connection': '', 'Roster Size': '32', 'Goalies on Roster': '',
    'Graduating Goalies': '', 'Program URL': 'https://loyolagreyhounds.com/sports/womens-lacrosse',
    'Questionnaire URL': '', Priority: '', Notes: 'Baltimore, MD', 'Last Updated': '2026-03-29',
  },
  // #22 Penn State
  {
    _rowIndex: 23, School: 'Penn State', Division: 'D1', Conference: 'Big Ten',
    'Academic Ranking': '#60', 'Acceptance Rate': '55%',
    'Head Coach': 'Kayla Treanor', 'Coach Email': '',
    'Coach Phone': '', 'Coach Background': 'Syracuse alum (2016), 4x All-American; 59-24 as Syracuse HC with back-to-back Final Fours; new at PSU in 2026',
    'Choate Connection': '', 'Roster Size': '33', 'Goalies on Roster': '',
    'Graduating Goalies': '', 'Program URL': 'https://gopsusports.com/sports/womens-lacrosse',
    'Questionnaire URL': '', Priority: '', Notes: 'State College, PA', 'Last Updated': '2026-03-29',
  },
  // #23 Georgetown
  {
    _rowIndex: 24, School: 'Georgetown', Division: 'D1', Conference: 'Big East',
    'Academic Ranking': '#22', 'Acceptance Rate': '12%',
    'Head Coach': 'Caitlyn Phipps', 'Coach Email': '',
    'Coach Phone': '', 'Coach Background': 'Maryland alum, Tewaaraton winner, 2x All-American; 12 yrs as UMD assistant, mentored 6 Tewaaraton winners',
    'Choate Connection': '', 'Roster Size': '32', 'Goalies on Roster': '',
    'Graduating Goalies': '', 'Program URL': 'https://guhoyas.com/sports/womens-lacrosse',
    'Questionnaire URL': '', Priority: '', Notes: 'Washington, DC', 'Last Updated': '2026-03-29',
  },
  // #24 Pittsburgh
  {
    _rowIndex: 25, School: 'Pittsburgh', Division: 'D1', Conference: 'ACC',
    'Academic Ranking': '#67', 'Acceptance Rate': '42%',
    'Head Coach': 'Emily Boissonneault', 'Coach Email': '',
    'Coach Phone': '', 'Coach Background': 'Detroit Mercy alum (2013), built Pitt program from scratch (2019); formerly JMU assistant during 2018 national title',
    'Choate Connection': '', 'Roster Size': '32', 'Goalies on Roster': '',
    'Graduating Goalies': '', 'Program URL': 'https://pittsburghpanthers.com/sports/womens-lacrosse',
    'Questionnaire URL': '', Priority: '', Notes: 'Pittsburgh, PA', 'Last Updated': '2026-03-29',
  },
  // #25 Richmond
  {
    _rowIndex: 26, School: 'Richmond', Division: 'D1', Conference: 'A-10',
    'Academic Ranking': '##2 Regional', 'Acceptance Rate': '24%',
    'Head Coach': 'Anne Harrington', 'Coach Email': '',
    'Coach Phone': '', 'Coach Background': 'William & Mary alum (2007), rose from 6-yr assistant to interim to HC at Richmond in 2022',
    'Choate Connection': '', 'Roster Size': '30', 'Goalies on Roster': '',
    'Graduating Goalies': '', 'Program URL': 'https://richmondspiders.com/sports/womens-lacrosse',
    'Questionnaire URL': '', Priority: '', Notes: 'Richmond, VA', 'Last Updated': '2026-03-29',
  },
  // ===== D3 PROGRAMS =====
  {
    _rowIndex: 27, School: 'Middlebury', Division: 'D3', Conference: 'NESCAC',
    'Academic Ranking': '#9 LAC', 'Acceptance Rate': '13%',
    'Head Coach': 'Kate Livesay', 'Coach Email': 'klivesay@middlebury.edu',
    'Coach Phone': '', 'Coach Background': '',
    'Choate Connection': 'NESCAC schools recruit heavily from NE prep',
    'Roster Size': '28', 'Goalies on Roster': '3', 'Graduating Goalies': '1 (2027)',
    'Program URL': 'https://athletics.middlebury.edu/sports/womens-lacrosse',
    'Questionnaire URL': '', Priority: '',
    Notes: 'Middlebury, VT. Perennial D3 power, top academics.', 'Last Updated': '2026-03-29',
  },
  {
    _rowIndex: 28, School: 'Tufts', Division: 'D3', Conference: 'NESCAC',
    'Academic Ranking': '#32', 'Acceptance Rate': '10%',
    'Head Coach': 'Courtney Shute', 'Coach Email': 'courtney.shute@tufts.edu',
    'Coach Phone': '', 'Coach Background': '',
    'Choate Connection': '', 'Roster Size': '26', 'Goalies on Roster': '2',
    'Graduating Goalies': '0', 'Program URL': 'https://gotuftsjumbos.com/sports/womens-lacrosse',
    'Questionnaire URL': '', Priority: '', Notes: 'Medford, MA. Near Boston.',
    'Last Updated': '2026-03-29',
  },
];

export const DEMO_HOCKEY_PROGRAMS: Program[] = [
  {
    _rowIndex: 2, School: 'Wisconsin', Division: 'D1', Conference: 'WCHA',
    'Academic Ranking': '#42', 'Acceptance Rate': '49%',
    'Head Coach': 'Mark Johnson', 'Coach Email': 'whockey@wisc.edu',
    'Coach Phone': '', 'Coach Background': '1980 Miracle on Ice team member',
    'Choate Connection': '', 'Roster Size': '28', 'Defenders on Roster': '8',
    'Graduating Defenders': '2 (2027)', 'Program URL': 'https://uwbadgers.com/sports/womens-ice-hockey',
    'Questionnaire URL': '', Priority: '', Notes: 'Dominant program',
    'Last Updated': '2026-03-29',
  },
  {
    _rowIndex: 3, School: 'Northeastern', Division: 'D1', Conference: 'Hockey East',
    'Academic Ranking': '#53', 'Acceptance Rate': '7%',
    'Head Coach': 'Dave Flint', 'Coach Email': 'whockey@northeastern.edu',
    'Coach Phone': '', 'Coach Background': '',
    'Choate Connection': '', 'Roster Size': '26', 'Defenders on Roster': '7',
    'Graduating Defenders': '2 (2028)', 'Program URL': 'https://nuhuskies.com/sports/womens-ice-hockey',
    'Questionnaire URL': '', Priority: '', Notes: 'Boston location',
    'Last Updated': '2026-03-29',
  },
  {
    _rowIndex: 4, School: 'Yale', Division: 'D1', Conference: 'ECAC',
    'Academic Ranking': '#5', 'Acceptance Rate': '5%',
    'Head Coach': 'Mark Bolding', 'Coach Email': 'whockey@yale.edu',
    'Coach Phone': '', 'Coach Background': '',
    'Choate Connection': 'Strong Choate-Yale pipeline', 'Roster Size': '25',
    'Defenders on Roster': '7', 'Graduating Defenders': '1 (2028)',
    'Program URL': 'https://yalebulldogs.com/sports/womens-ice-hockey',
    'Questionnaire URL': '', Priority: '', Notes: 'Close proximity to Choate, dual sport Ivy opportunity',
    'Last Updated': '2026-03-29',
  },
  {
    _rowIndex: 5, School: 'Harvard', Division: 'D1', Conference: 'ECAC',
    'Academic Ranking': '#3', 'Acceptance Rate': '3%',
    'Head Coach': 'Laura Bellamy', 'Coach Email': 'whockey@fas.harvard.edu',
    'Coach Phone': '(617) 495-2281', 'Coach Background': 'Harvard \'13 alum. Landry Family Head Coach. Replaced Katey Stone.',
    'Choate Connection': 'Choate sends students to Harvard', 'Roster Size': '25',
    'Defenders on Roster': '8', 'Graduating Defenders': '2 (2027)',
    'Program URL': 'https://gocrimson.com/sports/womens-ice-hockey',
    'Questionnaire URL': '', Priority: '', Notes: '',
    'Last Updated': '2026-03-29',
  },
  {
    _rowIndex: 6, School: 'Middlebury', Division: 'D3', Conference: 'NESCAC',
    'Academic Ranking': '#9 LAC', 'Acceptance Rate': '13%',
    'Head Coach': 'Bill Mandigo', 'Coach Email': 'whockey@middlebury.edu',
    'Coach Phone': '', 'Coach Background': 'Winningest D3 women\'s hockey coach ever (698-185-60). RETIRING June 2026 — successor TBD.',
    'Choate Connection': 'NESCAC recruits from NE prep schools',
    'Roster Size': '24', 'Defenders on Roster': '7', 'Graduating Defenders': '1 (2028)',
    'Program URL': 'https://athletics.middlebury.edu/sports/womens-ice-hockey',
    'Questionnaire URL': '', Priority: '', Notes: 'Could do dual sport here in D3',
    'Last Updated': '2026-03-29',
  },
  {
    _rowIndex: 7, School: 'Brown', Division: 'D1', Conference: 'ECAC',
    'Academic Ranking': '#13', 'Acceptance Rate': '5%',
    'Head Coach': 'Melanie Ruzzi', 'Coach Email': 'melanie_ruzzi@brown.edu',
    'Coach Phone': '401-440-5893', 'Coach Background': '',
    'Choate Connection': 'Ivy pipeline from Choate', 'Roster Size': '25',
    'Defenders on Roster': '7', 'Graduating Defenders': '1 (2028)',
    'Program URL': 'https://brownbears.com/sports/womens-ice-hockey',
    'Questionnaire URL': '', Priority: '', Notes: '',
    'Last Updated': '2026-03-29',
  },
  // ===== D3 PROGRAMS (25 total including Middlebury above) =====
  // --- NESCAC (highest priority — Lucie attends Choate Rosemary Hall) ---
  {
    _rowIndex: 8, School: 'Williams', Division: 'D3', Conference: 'NESCAC',
    'Academic Ranking': '#1 LAC', 'Acceptance Rate': '9%',
    'Head Coach': 'Meghan Gillis', 'Coach Email': 'Meghan.Gillis@williams.edu',
    'Coach Phone': '413-597-2899', 'Coach Background': 'Bowdoin \'07; 15th season; 2 NESCAC titles (2014, 2019); coached at Pomfret School (CT prep).',
    'Choate Connection': 'NESCAC — top target for NE prep players. Gillis coached at Pomfret School (CT prep).',
    'Roster Size': '', 'Defenders on Roster': '', 'Graduating Defenders': '',
    'Program URL': 'https://ephsports.williams.edu/sports/womens-ice-hockey',
    'Questionnaire URL': '', Priority: '', Notes: 'Williamstown, MA. #1 LAC. Elite academics + competitive NESCAC hockey.',
    'Last Updated': '2026-03-29',
  },
  {
    _rowIndex: 9, School: 'Amherst', Division: 'D3', Conference: 'NESCAC',
    'Academic Ranking': '#2 LAC', 'Acceptance Rate': '7%',
    'Head Coach': 'Jeff Matthews', 'Coach Email': 'jmatthews@amherst.edu',
    'Coach Phone': '413-542-2219', 'Coach Background': 'RPI \'95, Deerfield Academy \'91; 14th year; 209-81-34; 3 NESCAC titles in 5 yrs; played pro in Sweden.',
    'Choate Connection': 'NESCAC — strong NE prep pipeline. Matthews is Deerfield Academy alum.',
    'Roster Size': '', 'Defenders on Roster': '', 'Graduating Defenders': '',
    'Program URL': 'https://athletics.amherst.edu/sports/womens-ice-hockey',
    'Questionnaire URL': '', Priority: '', Notes: 'Amherst, MA. Perennial contender. 2023 NCAA D3 Championship Game.',
    'Last Updated': '2026-03-29',
  },
  {
    _rowIndex: 10, School: 'Bowdoin', Division: 'D3', Conference: 'NESCAC',
    'Academic Ranking': '#5 LAC', 'Acceptance Rate': '9%',
    'Head Coach': 'Marissa O\'Neil', 'Coach Email': 'moneil@bowdoin.edu',
    'Coach Phone': '', 'Coach Background': 'Bowdoin \'05; since 2010; 100+ wins; NESCAC Coach of Year 2013; holds 5 Bowdoin all-time records.',
    'Choate Connection': 'NESCAC — Brunswick, ME. NE prep pipeline.',
    'Roster Size': '', 'Defenders on Roster': '', 'Graduating Defenders': '',
    'Program URL': 'https://athletics.bowdoin.edu/sports/womens-ice-hockey',
    'Questionnaire URL': '', Priority: '', Notes: 'Brunswick, ME. 2013 NESCAC Champions.',
    'Last Updated': '2026-03-29',
  },
  {
    _rowIndex: 11, School: 'Colby', Division: 'D3', Conference: 'NESCAC',
    'Academic Ranking': '#11 LAC', 'Acceptance Rate': '10%',
    'Head Coach': 'Holley Tyng', 'Coach Email': 'holley.tyng@colby.edu',
    'Coach Phone': '207-859-4947', 'Coach Background': 'Providence College \'01; 10th year; 100th win Jan 2025; 3 NCAA bids in 4 yrs; 11 yrs at Dartmouth; USA Hockey U18 staff.',
    'Choate Connection': 'NESCAC — Waterville, ME. Tyng coached at Tabor Academy (NE prep).',
    'Roster Size': '', 'Defenders on Roster': '', 'Graduating Defenders': '',
    'Program URL': 'https://colbyathletics.com/sports/womens-ice-hockey',
    'Questionnaire URL': '', Priority: '', Notes: 'Waterville, ME. Rising program. USA Hockey coaching connections.',
    'Last Updated': '2026-03-29',
  },
  {
    _rowIndex: 12, School: 'Hamilton', Division: 'D3', Conference: 'NESCAC',
    'Academic Ranking': '#14 LAC', 'Acceptance Rate': '12%',
    'Head Coach': 'Kayte Holtz', 'Coach Email': 'kholtz@hamilton.edu',
    'Coach Phone': '315-859-4833', 'Coach Background': 'Bowdoin \'13; first-team All-American; HC since Oct 2023 after 10 yrs as assistant; best season ever 22-6-2 + first NCAA appearance (2022-23).',
    'Choate Connection': 'NESCAC — Clinton, NY. NE prep pipeline.',
    'Roster Size': '', 'Defenders on Roster': '', 'Graduating Defenders': '',
    'Program URL': 'https://athletics.hamilton.edu/sports/womens-ice-hockey',
    'Questionnaire URL': '', Priority: '', Notes: 'Clinton, NY. Program trending up. 2023 NCAA Semifinalist.',
    'Last Updated': '2026-03-29',
  },
  {
    _rowIndex: 13, School: 'Trinity (CT)', Division: 'D3', Conference: 'NESCAC',
    'Academic Ranking': '#46 LAC', 'Acceptance Rate': '30%',
    'Head Coach': 'Keith Maurice', 'Coach Email': 'keith.maurice@trincoll.edu',
    'Coach Phone': '', 'Coach Background': 'Norwich \'02; 11th season; formerly asst at Ohio State (D1); helped Norwich win 2011 NCAA D3 title.',
    'Choate Connection': 'NESCAC — Hartford, CT. ~30 min from Choate. Strongest geographic connection.',
    'Roster Size': '', 'Defenders on Roster': '', 'Graduating Defenders': '',
    'Program URL': 'https://bantamsports.com/sports/womens-ice-hockey',
    'Questionnaire URL': '', Priority: '', Notes: 'Hartford, CT. Closest NESCAC to Choate.',
    'Last Updated': '2026-03-29',
  },
  {
    _rowIndex: 14, School: 'Wesleyan', Division: 'D3', Conference: 'NESCAC',
    'Academic Ranking': '#18 LAC', 'Acceptance Rate': '14%',
    'Head Coach': 'Jodi McKenna', 'Coach Email': 'jamckenna@wesleyan.edu',
    'Coach Phone': '', 'Coach Background': 'Brown \'98; 19th season; 2010 Olympics asst coach (Team USA silver); also S&C coach; St. Lawrence MA.',
    'Choate Connection': 'NESCAC — Middletown, CT. ~25 min from Choate. Very strong geographic connection.',
    'Roster Size': '', 'Defenders on Roster': '', 'Graduating Defenders': '',
    'Program URL': 'https://athletics.wesleyan.edu/sports/womens-ice-hockey',
    'Questionnaire URL': '', Priority: '', Notes: 'Middletown, CT. Very close to Choate. Olympic coaching pedigree.',
    'Last Updated': '2026-03-29',
  },
  {
    _rowIndex: 15, School: 'Connecticut College', Division: 'D3', Conference: 'NESCAC',
    'Academic Ranking': '#46 LAC', 'Acceptance Rate': '39%',
    'Head Coach': 'Kristin Steele', 'Coach Email': 'Kristin.Steele@conncoll.edu',
    'Coach Phone': '860-439-2847', 'Coach Background': 'Maine \'94; 25th season; NESCAC & NE Hockey Writers Coach of Year 2015; previously asst at Niagara (D1).',
    'Choate Connection': 'NESCAC — New London, CT. ~45 min from Choate. CT connection.',
    'Roster Size': '', 'Defenders on Roster': '', 'Graduating Defenders': '',
    'Program URL': 'https://camelathletics.com/sports/womens-ice-hockey',
    'Questionnaire URL': '', Priority: '', Notes: 'New London, CT. Longest-tenured NESCAC WIH coach.',
    'Last Updated': '2026-03-29',
  },
  // --- SUNYAC ---
  {
    _rowIndex: 16, School: 'Plattsburgh State (SUNY)', Division: 'D3', Conference: 'SUNYAC',
    'Academic Ranking': 'Regional University (North)', 'Acceptance Rate': '55%',
    'Head Coach': 'Kevin Houle', 'Coach Email': '',
    'Coach Phone': '', 'Coach Background': 'Boston College \'86; 23rd season; 517-69-28 (.865); 7 NCAA D3 titles; 7x AHCA Coach of Year; drafted by Montreal Canadiens 1982.',
    'Choate Connection': '',
    'Roster Size': '', 'Defenders on Roster': '', 'Graduating Defenders': '',
    'Program URL': 'https://gocardinalsports.com/sports/womens-ice-hockey',
    'Questionnaire URL': '', Priority: '', Notes: 'Plattsburgh, NY. Most dominant D3 WIH program. 2026 SUNYAC Champs.',
    'Last Updated': '2026-03-29',
  },
  // --- NEHC (New England Hockey Conference) ---
  {
    _rowIndex: 17, School: 'Elmira', Division: 'D3', Conference: 'NEHC',
    'Academic Ranking': 'Regional (North)', 'Acceptance Rate': '72%',
    'Head Coach': 'Greg Haney', 'Coach Email': '',
    'Coach Phone': '', 'Coach Background': 'SUNY Cortland \'10; 3rd season; 2024 NCAA title game; 2024 NEHC champions; previously HC at SUNY Potsdam; asst at D1 Lindenwood.',
    'Choate Connection': '',
    'Roster Size': '', 'Defenders on Roster': '', 'Graduating Defenders': '',
    'Program URL': 'https://athletics.elmira.edu/sports/womens-ice-hockey',
    'Questionnaire URL': '', Priority: '', Notes: 'Elmira, NY. 8 NCAA championship appearances. 2024 national runner-up.',
    'Last Updated': '2026-03-29',
  },
  {
    _rowIndex: 18, School: 'Endicott', Division: 'D3', Conference: 'NEHC',
    'Academic Ranking': 'Regional (North)', 'Acceptance Rate': '78%',
    'Head Coach': 'Andrew McPhee', 'Coach Email': 'amcphee@endicott.edu',
    'Coach Phone': '', 'Coach Background': 'Middlebury \'99; 11th yr at Endicott; formerly HC at Trinity (CT) 2000-11; 2x NESCAC Coach of Year; 3x AHCA Regional Coach of Year; asst at Brown.',
    'Choate Connection': 'McPhee formerly coached at Trinity (CT) — understands NE prep talent.',
    'Roster Size': '', 'Defenders on Roster': '', 'Graduating Defenders': '',
    'Program URL': 'https://www.ecgulls.com/sports/wice/index',
    'Questionnaire URL': '', Priority: '', Notes: 'Beverly, MA. Coach is Middlebury alum with NESCAC background.',
    'Last Updated': '2026-03-29',
  },
  {
    _rowIndex: 19, School: 'Salve Regina', Division: 'D3', Conference: 'CNE',
    'Academic Ranking': 'Regional (North)', 'Acceptance Rate': '73%',
    'Head Coach': 'Meghan Toomey', 'Coach Email': '',
    'Coach Phone': '', 'Coach Background': 'St. Lawrence alum & Hall of Famer; pro player (Montreal Axion, HC Lugano); coached at Hill School, Kents Hill, KUA; asst at D1 Colgate.',
    'Choate Connection': 'Toomey coached at 3 NE prep schools — understands prep pipeline.',
    'Roster Size': '', 'Defenders on Roster': '', 'Graduating Defenders': '',
    'Program URL': 'https://salveathletics.com/sports/womens-ice-hockey',
    'Questionnaire URL': '', Priority: '', Notes: 'Newport, RI. New coach with prep school + D1 background.',
    'Last Updated': '2026-03-29',
  },
  {
    _rowIndex: 20, School: 'Nichols', Division: 'D3', Conference: 'NEHC',
    'Academic Ranking': 'Regional (North)', 'Acceptance Rate': '78%',
    'Head Coach': 'Michael Barrett', 'Coach Email': '',
    'Coach Phone': '', 'Coach Background': '5th season; 30 yrs at Quinnipiac (asst men\'s, then HC women\'s 6 seasons); former AWHCA VP & President; USA Hockey Level 5.',
    'Choate Connection': '',
    'Roster Size': '', 'Defenders on Roster': '', 'Graduating Defenders': '',
    'Program URL': 'https://nicholsathletics.com/sports/womens-ice-hockey',
    'Questionnaire URL': '', Priority: '', Notes: 'Dudley, MA. Coach has Quinnipiac D1 background.',
    'Last Updated': '2026-03-29',
  },
  // --- Little East Conference ---
  {
    _rowIndex: 21, School: 'Norwich', Division: 'D3', Conference: 'Little East',
    'Academic Ranking': 'Regional (North)', 'Acceptance Rate': '73%',
    'Head Coach': 'Justin Simpson', 'Coach Email': '',
    'Coach Phone': '', 'Coach Background': 'Laurentian Univ / MBA Providence College; 1st season; formerly assoc HC at Brown (D1); asst at RIT + Colby; LEC Coach of Year 2026; AHCA finalist.',
    'Choate Connection': 'Simpson previously coached at Colby (NESCAC) — knows NE prep talent.',
    'Roster Size': '', 'Defenders on Roster': '', 'Graduating Defenders': '',
    'Program URL': 'https://norwichathletics.com/sports/womens-ice-hockey',
    'Questionnaire URL': '', Priority: '', Notes: 'Northfield, VT. Historic program. Perfect LEC record 2025-26. Coach has Brown/Colby pedigree.',
    'Last Updated': '2026-03-29',
  },
  // --- UCHC (United Collegiate Hockey Conference) ---
  {
    _rowIndex: 22, School: 'Nazareth', Division: 'D3', Conference: 'UCHC',
    'Academic Ranking': 'Regional (North)', 'Acceptance Rate': '76%',
    'Head Coach': 'Chris Baudo', 'Coach Email': '',
    'Coach Phone': '', 'Coach Background': 'Hamilton \'00; 9th season; 116 wins in 6 yrs; 3 straight UCHC titles + 3 NCAA bids; 5x UCHC Coach of Year; 15 yrs at The Gunnery (CT prep).',
    'Choate Connection': 'Baudo coached at The Gunnery (CT prep) for 15 years — deep CT prep hockey roots.',
    'Roster Size': '', 'Defenders on Roster': '', 'Graduating Defenders': '',
    'Program URL': 'https://nazathletics.com/sports/womens-ice-hockey',
    'Questionnaire URL': '', Priority: '', Notes: 'Rochester, NY. 2026 NCAA semifinalist. Coach has CT prep roots (The Gunnery). Hamilton alum.',
    'Last Updated': '2026-03-29',
  },
  {
    _rowIndex: 23, School: 'Manhattanville', Division: 'D3', Conference: 'UCHC',
    'Academic Ranking': 'Regional (North)', 'Acceptance Rate': '74%',
    'Head Coach': 'Jennifer MacAskill', 'Coach Email': 'Jennifer.MacAskill@mville.edu',
    'Coach Phone': '914-798-2761', 'Coach Background': 'Mercyhurst \'18; 6th season; played D1 (captain, 2 CHA titles, 2 NCAA appearances); MS Sport Business from Manhattanville.',
    'Choate Connection': '',
    'Roster Size': '', 'Defenders on Roster': '', 'Graduating Defenders': '',
    'Program URL': 'https://govaliants.com/sports/womens-ice-hockey',
    'Questionnaire URL': '', Priority: '', Notes: 'Purchase, NY. Now Manhattanville University.',
    'Last Updated': '2026-03-29',
  },
  {
    _rowIndex: 24, School: 'Utica', Division: 'D3', Conference: 'UCHC',
    'Academic Ranking': 'Regional (North)', 'Acceptance Rate': '82%',
    'Head Coach': 'Melissa Lomanto', 'Coach Email': 'malomant@utica.edu',
    'Coach Phone': '315-792-5284', 'Coach Background': 'Utica \'05; 2nd season as HC; formerly HC at Morrisville State (89 wins, 2 CHC titles, 2x Coach of Year).',
    'Choate Connection': '',
    'Roster Size': '', 'Defenders on Roster': '', 'Graduating Defenders': '',
    'Program URL': 'https://uticapioneers.com/sports/womens-ice-hockey',
    'Questionnaire URL': '', Priority: '', Notes: 'Utica, NY. 2025 UCHC Coach of Year.',
    'Last Updated': '2026-03-29',
  },
  {
    _rowIndex: 25, School: 'Stevenson', Division: 'D3', Conference: 'UCHC',
    'Academic Ranking': 'Regional (North)', 'Acceptance Rate': '85%',
    'Head Coach': 'Ben Halford', 'Coach Email': '',
    'Coach Phone': '', 'Coach Background': 'Princeton alum; 1st season; played pro (AHL, ECHL); formerly asst at Penn State (D1, 3 CHA titles); 5 yrs asst at Wilkes (D3); founder Accelerate Goaltending.',
    'Choate Connection': '',
    'Roster Size': '', 'Defenders on Roster': '', 'Graduating Defenders': '',
    'Program URL': 'https://gomustangsports.com/sports/womens-ice-hockey',
    'Questionnaire URL': '', Priority: '', Notes: 'Stevenson, MD. New coach with D1 Penn State + Princeton pedigree.',
    'Last Updated': '2026-03-29',
  },
  {
    _rowIndex: 26, School: 'Chatham', Division: 'D3', Conference: 'UCHC',
    'Academic Ranking': 'Regional (North)', 'Acceptance Rate': '66%',
    'Head Coach': 'Mike O\'Grady', 'Coach Email': '',
    'Coach Phone': '', 'Coach Background': 'John Carroll \'14; 7th season; formerly asst at Mercyhurst (D1, CHC champ + NCAA Elite 8); asst at UMaine; previously HC at Nichols.',
    'Choate Connection': '',
    'Roster Size': '', 'Defenders on Roster': '', 'Graduating Defenders': '',
    'Program URL': 'https://gochathamcougars.com/sports/womens-ice-hockey',
    'Questionnaire URL': '', Priority: '', Notes: 'Pittsburgh, PA. 6 straight UCHC playoff appearances.',
    'Last Updated': '2026-03-29',
  },
  // --- NCHA (Northern Collegiate Hockey Association) ---
  {
    _rowIndex: 27, School: 'Adrian', Division: 'D3', Conference: 'NCHA',
    'Academic Ranking': 'Regional (Midwest)', 'Acceptance Rate': '67%',
    'Head Coach': 'Chad Davis', 'Coach Email': '',
    'Coach Phone': '', 'Coach Background': 'AIC alum; 9th season (returned 2024); 193-80-21; 4x NCHA Coach of Year; 2017 NCAA D3 National Coach of Year; played pro CHL.',
    'Choate Connection': '',
    'Roster Size': '', 'Defenders on Roster': '', 'Graduating Defenders': '',
    'Program URL': 'https://adrianbulldogs.com/sports/womens-ice-hockey',
    'Questionnaire URL': '', Priority: '', Notes: 'Adrian, MI. Historically strong — 150-37-10 in Davis\'s first stint.',
    'Last Updated': '2026-03-29',
  },
  // --- MIAC (Minnesota Intercollegiate Athletic Conference) ---
  {
    _rowIndex: 28, School: 'Gustavus Adolphus', Division: 'D3', Conference: 'MIAC',
    'Academic Ranking': '#150 LAC', 'Acceptance Rate': '72%',
    'Head Coach': 'Mike Carroll', 'Coach Email': '',
    'Coach Phone': '', 'Coach Background': 'MSU-Mankato alum; 27th season; 535-135-48 (.745); 2nd winningest all-time D3 WIH; 2023 NCAA D3 national champion; played pro baseball (Expos org).',
    'Choate Connection': '',
    'Roster Size': '', 'Defenders on Roster': '', 'Graduating Defenders': '',
    'Program URL': 'https://gogusties.com/sports/womens-ice-hockey',
    'Questionnaire URL': '', Priority: '', Notes: 'St. Peter, MN. 2023 National Champions.',
    'Last Updated': '2026-03-29',
  },
  // --- SUNYAC ---
  {
    _rowIndex: 29, School: 'SUNY Canton', Division: 'D3', Conference: 'SUNYAC',
    'Academic Ranking': 'Regional (North)', 'Acceptance Rate': '87%',
    'Head Coach': 'Kalie Hart', 'Coach Email': '',
    'Coach Phone': '', 'Coach Background': 'St. Lawrence alum (D1 captain); 4th season; formerly asst at Adrian (40-7-2 in 2 seasons); MS Sport Management.',
    'Choate Connection': '',
    'Roster Size': '', 'Defenders on Roster': '', 'Graduating Defenders': '',
    'Program URL': 'https://rooathletics.com/sports/womens-ice-hockey',
    'Questionnaire URL': '', Priority: '', Notes: 'Canton, NY.',
    'Last Updated': '2026-03-29',
  },
  {
    _rowIndex: 30, School: 'Morrisville State (SUNY)', Division: 'D3', Conference: 'SUNYAC',
    'Academic Ranking': 'Regional (North)', 'Acceptance Rate': '80%',
    'Head Coach': 'John Briggs', 'Coach Email': '',
    'Coach Phone': '', 'Coach Background': 'Cortland alum (coaching degree); 3rd season; formerly asst at SUNY Cortland (2 NEWHL finals); studied at Abertay Univ (Scotland).',
    'Choate Connection': '',
    'Roster Size': '', 'Defenders on Roster': '', 'Graduating Defenders': '',
    'Program URL': 'https://morrisvillemustangs.com/sports/womens-ice-hockey',
    'Questionnaire URL': '', Priority: '', Notes: 'Morrisville, NY.',
    'Last Updated': '2026-03-29',
  },
  // --- MAC (Middle Atlantic Conference) ---
  {
    _rowIndex: 31, School: 'Lebanon Valley', Division: 'D3', Conference: 'MAC',
    'Academic Ranking': 'Regional (North)', 'Acceptance Rate': '78%',
    'Head Coach': 'Matt Yingst', 'Coach Email': '',
    'Coach Phone': '', 'Coach Background': 'UConn alum; 9th season; played pro (AHL Hershey Bears, ECHL); 2025 MAC Coach of Year; led LVC to best-ever 17-8-1.',
    'Choate Connection': '',
    'Roster Size': '', 'Defenders on Roster': '', 'Graduating Defenders': '',
    'Program URL': 'https://godutchmen.com/sports/womens-ice-hockey',
    'Questionnaire URL': '', Priority: '', Notes: 'Annville, PA.',
    'Last Updated': '2026-03-29',
  },
];

export const DEMO_COACHES: Coach[] = [
  // ===== LACROSSE COACHES (verified from official athletics sites, March 2026) =====
  {
    _rowIndex: 2, Name: 'Jenny Levy', School: 'North Carolina', Sport: 'Lacrosse',
    Role: 'Head Coach', Email: 'wlax@unc.edu', Phone: '',
    'Alma Mater': '', 'Years at Program': '20+',
    Background: 'Led UNC to 3 NCAA titles; one of the winningest coaches in D1 history',
    'Choate Connection': '', Notes: '', 'Last Updated': '2026-03-29',
  },
  {
    _rowIndex: 3, Name: 'Danielle Spencer', School: 'Stanford', Sport: 'Lacrosse',
    Role: 'Head Coach', Email: '', Phone: '',
    'Alma Mater': 'Northwestern (2010)', 'Years at Program': '7',
    Background: '3x NCAA champion as Northwestern player, 2x All-American; swept Pac-12 titles in 2021/22/24',
    'Choate Connection': '', Notes: '', 'Last Updated': '2026-03-29',
  },
  {
    _rowIndex: 4, Name: 'Cathy Reese', School: 'Maryland', Sport: 'Lacrosse',
    Role: 'Head Coach', Email: '', Phone: '',
    'Alma Mater': 'Maryland (1998)', 'Years at Program': '18',
    Background: '5x NCAA champion coach at Maryland, 350+ career wins, 2025 IWLCA Hall of Fame',
    'Choate Connection': '', Notes: '', 'Last Updated': '2026-03-29',
  },
  {
    _rowIndex: 5, Name: 'Cindy Timchal', School: 'Navy', Sport: 'Lacrosse',
    Role: 'Head Coach', Email: '', Phone: '',
    'Alma Mater': 'West Chester', 'Years at Program': '19',
    Background: 'NCAA all-time wins leader (600+), 8x NCAA champion at Maryland; built Navy D1 program from scratch',
    'Choate Connection': '', Notes: '', 'Last Updated': '2026-03-29',
  },
  {
    _rowIndex: 6, Name: 'Regy Thorpe', School: 'Syracuse', Sport: 'Lacrosse',
    Role: 'Head Coach', Email: 'rjthorpe@syr.edu', Phone: '',
    'Alma Mater': 'Syracuse', 'Years at Program': '1 (14 total with program)',
    Background: 'NCAA champion as SU player (1993), 10 yrs as SU assistant, came from Florida as associate HC',
    'Choate Connection': '', Notes: '', 'Last Updated': '2026-03-29',
  },
  {
    _rowIndex: 7, Name: 'Tim McCormack', School: 'Johns Hopkins', Sport: 'Lacrosse',
    Role: 'Head Coach', Email: '', Phone: '',
    'Alma Mater': 'UMass (2012)', 'Years at Program': '4',
    Background: 'Former UMass goalie and captain; Northwestern assistant for 6 years; Arizona State HC before JHU',
    'Choate Connection': '', Notes: '', 'Last Updated': '2026-03-29',
  },
  {
    _rowIndex: 8, Name: 'Amanda O\'Leary', School: 'Florida', Sport: 'Lacrosse',
    Role: 'Head Coach', Email: '', Phone: '',
    'Alma Mater': 'Temple (1988)', 'Years at Program': '17',
    Background: 'NCAA champion and 3x All-American as Temple player; US Lacrosse Hall of Fame; 2026 IWLCA Hall of Fame',
    'Choate Connection': '', Notes: '', 'Last Updated': '2026-03-29',
  },
  {
    _rowIndex: 9, Name: 'Erica Bamford', School: 'Yale', Sport: 'Lacrosse',
    Role: 'Head Coach', Email: 'erica.bamford@yale.edu', Phone: '',
    'Alma Mater': '', 'Years at Program': '',
    Background: 'Joel E. Smilow \'54 Head Coach. Former US National Team. 2024 Ivy League Coach of the Year.',
    'Choate Connection': 'Yale has strong Choate pipeline', Notes: '', 'Last Updated': '2026-03-29',
  },
  {
    _rowIndex: 10, Name: 'Hannah Nielsen', School: 'Michigan', Sport: 'Lacrosse',
    Role: 'Head Coach', Email: 'wlax@umich.edu', Phone: '',
    'Alma Mater': 'Northwestern', 'Years at Program': '5',
    Background: 'Former Tewaaraton Award winner, led Michigan to rapid rise',
    'Choate Connection': '', Notes: 'Runs summer camps at Michigan', 'Last Updated': '2026-03-29',
  },
  {
    _rowIndex: 11, Name: 'Allison Kwolek', School: 'Clemson', Sport: 'Lacrosse',
    Role: 'Head Coach', Email: '', Phone: '',
    'Alma Mater': 'William & Mary', 'Years at Program': '4',
    Background: 'William & Mary Hall of Fame, US National Team; built Richmond to 64-16 record before becoming inaugural Clemson HC',
    'Choate Connection': '', Notes: '', 'Last Updated': '2026-03-29',
  },
  {
    _rowIndex: 12, Name: 'Joe Spallina', School: 'Stony Brook', Sport: 'Lacrosse',
    Role: 'Head Coach', Email: '', Phone: '',
    'Alma Mater': 'Adelphi (1996)', 'Years at Program': '14',
    Background: '224-45 at Stony Brook, 12 straight NCAA bids; 3x D2 champion at Adelphi; US women\'s national team assistant',
    'Choate Connection': '', Notes: '', 'Last Updated': '2026-03-29',
  },
  {
    _rowIndex: 13, Name: 'Kelly Amonte Hiller', School: 'Northwestern', Sport: 'Lacrosse',
    Role: 'Head Coach', Email: 'h-amonte@northwestern.edu', Phone: '',
    'Alma Mater': 'Maryland', 'Years at Program': '23',
    Background: '7x NCAA champion coach, former US National Team',
    'Choate Connection': '', Notes: '', 'Last Updated': '2026-03-29',
  },
  {
    _rowIndex: 14, Name: 'Christine Halfpenny', School: 'Notre Dame', Sport: 'Lacrosse',
    Role: 'Head Coach', Email: '', Phone: '',
    'Alma Mater': 'Virginia Tech', 'Years at Program': '15',
    Background: 'NCAA tournament in 9 of 11 completed seasons at ND; formerly HC at William & Mary',
    'Choate Connection': '', Notes: '', 'Last Updated': '2026-03-29',
  },
  {
    _rowIndex: 15, Name: 'Ann Elliott Whidden', School: 'Colorado', Sport: 'Lacrosse',
    Role: 'Head Coach', Email: '', Phone: '',
    'Alma Mater': 'Northwestern (2007)', 'Years at Program': '14',
    Background: '3x NCAA champion as Northwestern player, 3x as NU assistant; built CU program from inception',
    'Choate Connection': '', Notes: '', 'Last Updated': '2026-03-29',
  },
  {
    _rowIndex: 16, Name: 'Acacia Walker-Weinstein', School: 'Boston College', Sport: 'Lacrosse',
    Role: 'Head Coach', Email: 'walkerau@bc.edu', Phone: '',
    'Alma Mater': 'Northwestern', 'Years at Program': '10+',
    Background: 'Former Northwestern All-American, led BC to consecutive Final Fours',
    'Choate Connection': '', Notes: '', 'Last Updated': '2026-03-29',
  },
  {
    _rowIndex: 17, Name: 'Michelle Tumolo', School: 'Army', Sport: 'Lacrosse',
    Role: 'Head Coach', Email: '', Phone: '',
    'Alma Mater': 'Syracuse', 'Years at Program': '5',
    Background: 'One of Syracuse\'s all-time great attackers, Tewaaraton finalist; formerly HC at Wagner, assistant at Oregon/Florida',
    'Choate Connection': '', Notes: '', 'Last Updated': '2026-03-29',
  },
  {
    _rowIndex: 18, Name: 'Kerstin Kimel', School: 'Duke', Sport: 'Lacrosse',
    Role: 'Head Coach', Email: 'kmkimel@duke.edu', Phone: '',
    'Alma Mater': 'Maryland (1993)', 'Years at Program': '30',
    Background: '1992 NCAA champion as Maryland player; only HC in Duke women\'s lacrosse history since program inception in 1996',
    'Choate Connection': '', Notes: '', 'Last Updated': '2026-03-29',
  },
  {
    _rowIndex: 19, Name: 'Liza Kelly', School: 'Denver', Sport: 'Lacrosse',
    Role: 'Head Coach', Email: '', Phone: '',
    'Alma Mater': 'Delaware', 'Years at Program': '19',
    Background: '3x All-American at Delaware, US National Team; 6 straight NCAA bids at DU; formerly HC at Boston University',
    'Choate Connection': '', Notes: '', 'Last Updated': '2026-03-29',
  },
  {
    _rowIndex: 20, Name: 'Jenn Cook', School: 'Princeton', Sport: 'Lacrosse',
    Role: 'Head Coach', Email: 'jc30@princeton.edu', Phone: '',
    'Alma Mater': '', 'Years at Program': '',
    Background: 'Promoted after Chris Sailer retired (36-yr career). 7 Ivy League titles as assistant.',
    'Choate Connection': 'Strong Choate pipeline to Ivy', Notes: '', 'Last Updated': '2026-03-29',
  },
  {
    _rowIndex: 21, Name: 'Sonia LaMonica', School: 'Virginia', Sport: 'Lacrosse',
    Role: 'Head Coach', Email: '', Phone: '',
    'Alma Mater': 'Maryland (2003)', 'Years at Program': '3',
    Background: '2x national champion as Maryland player, 1st-team All-American; 13-yr HC at Towson; Australian-born',
    'Choate Connection': '', Notes: '', 'Last Updated': '2026-03-29',
  },
  {
    _rowIndex: 22, Name: 'Jen Adams', School: 'Loyola Maryland', Sport: 'Lacrosse',
    Role: 'Head Coach', Email: '', Phone: '',
    'Alma Mater': 'Maryland (2001)', 'Years at Program': '18',
    Background: 'NCAA career scoring record holder, 4x national champion as player; US Lacrosse Hall of Fame; Australian-born',
    'Choate Connection': '', Notes: '', 'Last Updated': '2026-03-29',
  },
  {
    _rowIndex: 23, Name: 'Kayla Treanor', School: 'Penn State', Sport: 'Lacrosse',
    Role: 'Head Coach', Email: '', Phone: '',
    'Alma Mater': 'Syracuse (2016)', 'Years at Program': '1',
    Background: '4x 1st-team All-American at Syracuse; 59-24 as Syracuse HC with back-to-back Final Fours; new at PSU in 2026',
    'Choate Connection': '', Notes: '', 'Last Updated': '2026-03-29',
  },
  {
    _rowIndex: 24, Name: 'Caitlyn Phipps', School: 'Georgetown', Sport: 'Lacrosse',
    Role: 'Head Coach', Email: '', Phone: '',
    'Alma Mater': 'Maryland', 'Years at Program': '2',
    Background: 'Tewaaraton winner, 2x All-American at Maryland; 12 yrs as UMD assistant, mentored 6 Tewaaraton winners',
    'Choate Connection': '', Notes: '', 'Last Updated': '2026-03-29',
  },
  {
    _rowIndex: 25, Name: 'Emily Boissonneault', School: 'Pittsburgh', Sport: 'Lacrosse',
    Role: 'Head Coach', Email: '', Phone: '',
    'Alma Mater': 'Detroit Mercy (2013)', 'Years at Program': '7',
    Background: 'Built Pitt program from scratch as inaugural HC (2019); formerly JMU assistant during 2018 national championship',
    'Choate Connection': '', Notes: '', 'Last Updated': '2026-03-29',
  },
  {
    _rowIndex: 26, Name: 'Anne Harrington', School: 'Richmond', Sport: 'Lacrosse',
    Role: 'Head Coach', Email: '', Phone: '',
    'Alma Mater': 'William & Mary (2007)', 'Years at Program': '8',
    Background: 'Rose from 6-yr assistant to interim to permanent HC at Richmond in 2022',
    'Choate Connection': '', Notes: '', 'Last Updated': '2026-03-29',
  },
  // ===== HOCKEY COACHES =====
  {
    _rowIndex: 27, Name: 'Mark Bolding', School: 'Yale', Sport: 'Hockey',
    Role: 'Head Coach', Email: 'whockey@yale.edu', Phone: '',
    'Alma Mater': '', 'Years at Program': '',
    Background: '',
    'Choate Connection': 'Yale has strong Choate pipeline', Notes: '', 'Last Updated': '2026-03-29',
  },
  {
    _rowIndex: 28, Name: 'Laura Bellamy', School: 'Harvard', Sport: 'Hockey',
    Role: 'Head Coach', Email: 'whockey@fas.harvard.edu', Phone: '(617) 495-2281',
    'Alma Mater': 'Harvard \'13', 'Years at Program': '3',
    Background: 'Landry Family Head Coach. Harvard alum, replaced Katey Stone.',
    'Choate Connection': 'Choate sends students to Harvard', Notes: '', 'Last Updated': '2026-03-29',
  },
  {
    _rowIndex: 29, Name: 'Melanie Ruzzi', School: 'Brown', Sport: 'Hockey',
    Role: 'Head Coach', Email: 'melanie_ruzzi@brown.edu', Phone: '401-440-5893',
    'Alma Mater': '', 'Years at Program': '',
    Background: '',
    'Choate Connection': 'Ivy pipeline from Choate', Notes: '', 'Last Updated': '2026-03-29',
  },
];

// Real events from Matthew's Google Sheet "2025/2026 Lax Clinics/Showcases"
export const DEMO_EVENTS: CalendarEvent[] = [
  // ---- PAST EVENTS (completed) ----
  {
    _rowIndex: 2, 'Event Name': 'Peak Goalie Training', Sport: 'Lacrosse',
    Date: '2026-01-25', 'End Date': '2026-01-25', Location: 'Springfield College',
    Type: 'Camp', 'Coaches Attending': '', Cost: '$200',
    'Registration URL': 'https://peakgoalie.com/2026-girls-summer-goalie-camp', 'Registration Deadline': '',
    Status: 'Attended', Notes: 'Sponsor: Peakgoalie/MYLA. 9am-12pm. Summer sessions: Jun 22-24 & Jul 20-22 at Springfield College.',
  },
  {
    _rowIndex: 3, 'Event Name': 'BC Clinix', Sport: 'Lacrosse',
    Date: '2026-01-11', 'End Date': '2026-01-11', Location: 'Boston College',
    Type: 'Camp', 'Coaches Attending': 'BC coaching staff', Cost: '',
    'Registration URL': 'https://bostoncollegewomenslacrosse.totalcamps.com/', 'Registration Deadline': '',
    Status: 'Attended', Notes: '9am-3pm.',
  },
  {
    _rowIndex: 4, 'Event Name': 'Prep Showcase', Sport: 'Lacrosse',
    Date: '2026-01-18', 'End Date': '2026-01-18', Location: 'Bryant University, RI',
    Type: 'Showcase', 'Coaches Attending': '', Cost: '',
    'Registration URL': 'https://apexlacrosseevents.com/showcase/girls-prep-showcase/', 'Registration Deadline': '',
    Status: 'Attended', Notes: 'Sponsor: ApexgirlsLaxevents. Hockey conflict — application process.',
  },
  {
    _rowIndex: 5, 'Event Name': 'Trinity Clinic', Sport: 'Lacrosse',
    Date: '2025-03-15', 'End Date': '2025-03-15', Location: 'Trinity College, Hartford CT',
    Type: 'Camp', 'Coaches Attending': 'Trinity coaching staff', Cost: '$50',
    'Registration URL': 'https://www.trinitywlacrossecamps.com/', 'Registration Deadline': '',
    Status: 'Attended', Notes: '',
  },
  // ---- UPCOMING EVENTS ----
  {
    _rowIndex: 6, 'Event Name': 'American Select Tryouts Northeast', Sport: 'Lacrosse',
    Date: '2026-04-12', 'End Date': '2026-04-12', Location: 'UNH (University of New Hampshire)',
    Type: 'Tryout', 'Coaches Attending': '', Cost: '$135',
    'Registration URL': 'https://americanselectlacrosse.com/2026-regional-tryouts-for-main-event',
    'Registration Deadline': '',
    Status: 'Registered', Notes: '2028/2029: 10am-12pm. Tryout format.',
  },
  {
    _rowIndex: 7, 'Event Name': 'American Select Tryouts MASS', Sport: 'Lacrosse',
    Date: '2026-04-26', 'End Date': '2026-04-26', Location: 'The Rivers School, Weston, MA',
    Type: 'Tryout', 'Coaches Attending': '', Cost: '$135',
    'Registration URL': 'https://americanselectlacrosse.com/2026-regional-tryouts-for-main-event',
    'Registration Deadline': '',
    Status: 'Registered', Notes: '9am-12pm.',
  },
  {
    _rowIndex: 8, 'Event Name': 'All American Tryouts (New Balance)', Sport: 'Lacrosse',
    Date: '2026-05-03', 'End Date': '2026-05-03', Location: 'Union Point Sports Complex, MA',
    Type: 'Tryout', 'Coaches Attending': '', Cost: '$170',
    'Registration URL': 'https://events.r2it.com/lacrosse/AllAmerica26/tryouts',
    'Registration Deadline': '',
    Status: 'Interested', Notes: 'Not yet registered. Command division (2029). Tryout format.',
  },
  {
    _rowIndex: 9, 'Event Name': 'Champions Cup', Sport: 'Lacrosse',
    Date: '2026-06-20', 'End Date': '2026-06-21', Location: 'Boyds, MD',
    Type: 'Tournament', 'Coaches Attending': 'Multiple D1 coaches (IWLCA event)', Cost: '',
    'Registration URL': 'https://iwlcarecruiting.com/tournaments/iwlca-champions-cup-v2/',
    'Registration Deadline': '',
    Status: 'Registered', Notes: 'IWLCA Champions Cup. NH29 Purple. 748 miles, 2 overnights.',
  },
  {
    _rowIndex: 10, 'Event Name': 'NE Showcase', Sport: 'Lacrosse',
    Date: '2026-06-14', 'End Date': '2026-06-14', Location: 'Afrim\'s Sports Park / UAlbany, NY',
    Type: 'Showcase', 'Coaches Attending': '', Cost: '',
    'Registration URL': 'https://lpswag.com/tournament-info/',
    'Registration Deadline': '',
    Status: 'Registered', Notes: 'Northeast Summer Showcase. NH29 Purple. 182 miles.',
  },
  {
    _rowIndex: 11, 'Event Name': 'IWLCA New England Cup', Sport: 'Lacrosse',
    Date: '2026-06-26', 'End Date': '2026-06-28', Location: 'Amherst, MA',
    Type: 'Tournament', 'Coaches Attending': 'IWLCA coaches', Cost: '',
    'Registration URL': 'https://iwlcarecruiting.com/tournaments/iwlca-new-england-cup/',
    'Registration Deadline': '',
    Status: 'Registered', Notes: 'NH29Purple. 192 miles.',
  },
  {
    _rowIndex: 12, 'Event Name': 'Top Threat Championship', Sport: 'Lacrosse',
    Date: '2026-07-10', 'End Date': '2026-07-12', Location: 'Basking Ridge, NJ (Pingry School area)',
    Type: 'Tournament', 'Coaches Attending': '', Cost: '$2,200 team fee',
    'Registration URL': 'https://www.topthreattournaments.com/event/top-threat-championship/',
    'Registration Deadline': '',
    Status: 'Registered', Notes: 'NH29Purple. 348 miles, 3 overnights, 4 food days.',
  },
  {
    _rowIndex: 13, 'Event Name': 'Mid-Atlantic Showcase', Sport: 'Lacrosse',
    Date: '2026-07-17', 'End Date': '2026-07-19', Location: 'MD State Fairgrounds, Timonium, MD',
    Type: 'Tournament', 'Coaches Attending': '', Cost: '',
    'Registration URL': 'https://lacrosse.sincsports.com/TTContent.aspx?tid=MIDATL',
    'Registration Deadline': '',
    Status: 'Registered', Notes: 'NH29Purple. 652 miles, 3 overnights, 4 food days.',
  },
  {
    _rowIndex: 14, 'Event Name': 'American Select Main Event', Sport: 'Lacrosse',
    Date: '2026-07-23', 'End Date': '2026-07-25', Location: 'DE Turf Sports Complex, Milford, DE',
    Type: 'Tournament', 'Coaches Attending': '', Cost: '',
    'Registration URL': 'https://americanselectlacrosse.com/main-event',
    'Registration Deadline': '',
    Status: 'TBD', Notes: 'Individual Showcase July 22. Registration TBD.',
  },
  {
    _rowIndex: 15, 'Event Name': 'All-America Lacrosse Main Event', Sport: 'Lacrosse',
    Date: '2026-07-24', 'End Date': '2026-07-26', Location: 'Baltimore, MD',
    Type: 'Tournament', 'Coaches Attending': '', Cost: '',
    'Registration URL': 'https://www.allamericalacrosse.com/',
    'Registration Deadline': '',
    Status: 'Interested', Notes: 'Corrigan Sports Enterprises. Not registered.',
  },
  {
    _rowIndex: 16, 'Event Name': 'Lake Placid Summit Classic', Sport: 'Lacrosse',
    Date: '2026-07-27', 'End Date': '2026-07-29', Location: 'Lake Placid, NY',
    Type: 'Tournament', 'Coaches Attending': '', Cost: '',
    'Registration URL': 'https://summitlacrosseventures.com/tournaments/lake-placid-summit-classic/',
    'Registration Deadline': '',
    Status: 'Registered', Notes: 'Scholastic division, 5 guaranteed games. Daughter\'s Nation. 454 miles, 4 overnights.',
  },
  {
    _rowIndex: 17, 'Event Name': 'Northeast Elite Recruiting Showcase', Sport: 'Lacrosse',
    Date: '2026-12-01', 'End Date': '2026-12-01', Location: 'FSA Farmington, CT (expected)',
    Type: 'Showcase', 'Coaches Attending': 'D1/D3 coaches', Cost: '',
    'Registration URL': 'https://nerslax.com/',
    'Registration Deadline': '',
    Status: 'TBD', Notes: 'December 2026 — exact date TBD. Typically early December.',
  },
  // ---- HOCKEY EVENTS (details TBD) ----
  {
    _rowIndex: 18, 'Event Name': 'Harvard HS Elite Hockey Camp', Sport: 'Hockey',
    Date: '2026-07-07', 'End Date': '2026-07-09', Location: 'Harvard University, Cambridge, MA',
    Type: 'Camp', 'Coaches Attending': 'Coach Laura Bellamy + Harvard staff', Cost: '',
    'Registration URL': 'https://www.crimsonhockey.com/camps-at-harvard.html',
    'Registration Deadline': '',
    Status: 'Interested', Notes: 'High School Elite Camp. Jul 7-9, 2026.',
  },
  {
    _rowIndex: 19, 'Event Name': 'Middlebury Women\'s Hockey Camp', Sport: 'Hockey',
    Date: '2026-07-01', 'End Date': '2026-07-01', Location: 'Middlebury College, VT',
    Type: 'Camp', 'Coaches Attending': 'Middlebury coaching staff + NESCAC guest coaches', Cost: '',
    'Registration URL': 'https://www.middleburywomenshockeycamp.com/hockey-camp-.cfm',
    'Registration Deadline': '',
    Status: 'Interested', Notes: 'Exact dates TBD. For players with collegiate aspirations.',
  },
  {
    _rowIndex: 20, 'Event Name': 'Brown Elite Summer Hockey Camp', Sport: 'Hockey',
    Date: '2026-07-01', 'End Date': '2026-07-01', Location: 'Brown University, Providence, RI',
    Type: 'Camp', 'Coaches Attending': 'Coach Mel Ruzzi + Brown staff', Cost: '',
    'Registration URL': 'https://sportscamps.brown.edu/',
    'Registration Deadline': '',
    Status: 'Interested', Notes: 'For entering grades 9-12. Exact dates TBD.',
  },
];

export const DEMO_CONTACT_LOG: ContactLogEntry[] = [];

export const DEMO_TIMELINE: TimelineEvent[] = [
  { _rowIndex: 2, Date: '2026-03-29', Event: 'Recruiting dashboard launched', Category: 'Milestone', Sport: 'Both', Notes: '', Completed: 'true' },
  { _rowIndex: 3, Date: '2026-04-01', Event: 'Begin filling out recruiting questionnaires', Category: 'Task', Sport: 'Both', Notes: 'Start with top 10 targets', Completed: '' },
  { _rowIndex: 4, Date: '2026-04-12', Event: 'American Select Tryouts NE @ UNH', Category: 'Task', Sport: 'Lacrosse', Notes: '', Completed: '' },
  { _rowIndex: 5, Date: '2026-04-26', Event: 'American Select Tryouts MASS', Category: 'Task', Sport: 'Lacrosse', Notes: '', Completed: '' },
  { _rowIndex: 6, Date: '2026-06-01', Event: 'Update highlight reel — spring lacrosse season', Category: 'Task', Sport: 'Lacrosse', Notes: '', Completed: '' },
  { _rowIndex: 7, Date: '2026-06-14', Event: 'NE Showcase — Albany', Category: 'Task', Sport: 'Lacrosse', Notes: 'NH29 Purple', Completed: '' },
  { _rowIndex: 8, Date: '2026-06-20', Event: 'Champions Cup — Boyds MD', Category: 'Task', Sport: 'Lacrosse', Notes: 'NH29 Purple, 2 overnights', Completed: '' },
  { _rowIndex: 9, Date: '2026-07-10', Event: 'Top Threat — Basking Ridge NJ', Category: 'Task', Sport: 'Lacrosse', Notes: 'NH29 Purple, 3 overnights', Completed: '' },
  { _rowIndex: 10, Date: '2026-07-17', Event: 'Mid-Atlantic — MD State Fairgrounds', Category: 'Task', Sport: 'Lacrosse', Notes: 'NH29 Purple, 3 overnights', Completed: '' },
  { _rowIndex: 11, Date: '2026-07-26', Event: 'Lake Placid Tournament', Category: 'Task', Sport: 'Lacrosse', Notes: 'Daughter\'s Nation, 4 overnights', Completed: '' },
  { _rowIndex: 12, Date: '2026-09-01', Event: 'Sophomore year begins (4th form)', Category: 'Milestone', Sport: 'Both', Notes: '', Completed: '' },
  { _rowIndex: 13, Date: '2026-12-01', Event: 'Northeast Elite Recruiting Showcase', Category: 'Task', Sport: 'Lacrosse', Notes: 'Date TBD', Completed: '' },
  { _rowIndex: 14, Date: '2027-06-15', Event: 'NCAA D1 contact period opens (after soph year)', Category: 'NCAA', Sport: 'Both', Notes: 'Coaches can call/text after this date', Completed: '' },
  { _rowIndex: 15, Date: '2027-09-01', Event: 'Junior year — prime recruiting window', Category: 'Milestone', Sport: 'Both', Notes: 'Unofficial visits, coach conversations', Completed: '' },
  { _rowIndex: 16, Date: '2028-06-01', Event: 'Target for verbal commitment decisions', Category: 'Milestone', Sport: 'Both', Notes: '', Completed: '' },
  { _rowIndex: 17, Date: '2028-11-01', Event: 'Early Decision/Action applications due', Category: 'Academic', Sport: 'Both', Notes: '', Completed: '' },
  { _rowIndex: 18, Date: '2029-02-01', Event: 'NLI signing day (D1)', Category: 'NCAA', Sport: 'Both', Notes: '', Completed: '' },
];
