import type { Program, Coach, CalendarEvent, ContactLogEntry, TimelineEvent } from './types';

// Demo data — will be replaced by live Google Sheets data once OAuth is configured

export const DEMO_LACROSSE_PROGRAMS: Program[] = [
  {
    _rowIndex: 2, School: 'Northwestern', Division: 'D1', Conference: 'Big Ten',
    'Academic Ranking': '#9', 'Acceptance Rate': '7%',
    'Head Coach': 'Kelly Amonte Hiller', 'Coach Email': 'lacrosse@northwestern.edu',
    'Coach Phone': '', 'Coach Background': 'Former US National Team, 7x NCAA Champion coach',
    'Choate Connection': '', 'Roster Size': '35', 'Goalies on Roster': '3',
    'Graduating Goalies': '1 (2027)', 'Program URL': 'https://nusports.com/sports/womens-lacrosse',
    'Questionnaire URL': '', Priority: 'Dream', Notes: '', 'Last Updated': '2026-03-29',
  },
  {
    _rowIndex: 3, School: 'Boston College', Division: 'D1', Conference: 'ACC',
    'Academic Ranking': '#36', 'Acceptance Rate': '17%',
    'Head Coach': 'Acacia Walker-Weinstein', 'Coach Email': 'wlax@bc.edu',
    'Coach Phone': '', 'Coach Background': 'Former Northwestern All-American',
    'Choate Connection': '', 'Roster Size': '33', 'Goalies on Roster': '3',
    'Graduating Goalies': '1 (2028)', 'Program URL': 'https://bceagles.com/sports/womens-lacrosse',
    'Questionnaire URL': '', Priority: 'Target', Notes: '', 'Last Updated': '2026-03-29',
  },
  {
    _rowIndex: 4, School: 'North Carolina', Division: 'D1', Conference: 'ACC',
    'Academic Ranking': '#22', 'Acceptance Rate': '17%',
    'Head Coach': 'Jenny Levy', 'Coach Email': 'wlax@unc.edu',
    'Coach Phone': '', 'Coach Background': 'Led UNC to 3 NCAA titles',
    'Choate Connection': '', 'Roster Size': '34', 'Goalies on Roster': '3',
    'Graduating Goalies': '0', 'Program URL': 'https://goheels.com/sports/womens-lacrosse',
    'Questionnaire URL': '', Priority: 'Dream', Notes: '', 'Last Updated': '2026-03-29',
  },
  {
    _rowIndex: 5, School: 'Syracuse', Division: 'D1', Conference: 'ACC',
    'Academic Ranking': '#62', 'Acceptance Rate': '44%',
    'Head Coach': 'Kayla Treanor', 'Coach Email': 'wlax@syr.edu',
    'Coach Phone': '', 'Coach Background': 'Former SU All-American, Tewaaraton winner',
    'Choate Connection': '', 'Roster Size': '32', 'Goalies on Roster': '2',
    'Graduating Goalies': '1 (2027)', 'Program URL': 'https://cuse.com/sports/womens-lacrosse',
    'Questionnaire URL': '', Priority: 'Target', Notes: '', 'Last Updated': '2026-03-29',
  },
  {
    _rowIndex: 6, School: 'Princeton', Division: 'D1', Conference: 'Ivy League',
    'Academic Ranking': '#1', 'Acceptance Rate': '4%',
    'Head Coach': 'Chris Sailer', 'Coach Email': 'wlax@princeton.edu',
    'Coach Phone': '', 'Coach Background': '',
    'Choate Connection': 'Strong Choate pipeline to Ivy', 'Roster Size': '30',
    'Goalies on Roster': '3', 'Graduating Goalies': '1 (2028)',
    'Program URL': 'https://goprincetontigers.com/sports/womens-lacrosse',
    'Questionnaire URL': '', Priority: 'Dream', Notes: 'Ivy — no athletic scholarships but strong aid',
    'Last Updated': '2026-03-29',
  },
  {
    _rowIndex: 7, School: 'Yale', Division: 'D1', Conference: 'Ivy League',
    'Academic Ranking': '#5', 'Acceptance Rate': '5%',
    'Head Coach': 'Erica LaGrow', 'Coach Email': 'wlax@yale.edu',
    'Coach Phone': '', 'Coach Background': '',
    'Choate Connection': 'Strong Choate-Yale pipeline', 'Roster Size': '30',
    'Goalies on Roster': '2', 'Graduating Goalies': '1 (2028)',
    'Program URL': 'https://yalebulldogs.com/sports/womens-lacrosse',
    'Questionnaire URL': '', Priority: 'Dream', Notes: 'Close proximity to Choate',
    'Last Updated': '2026-03-29',
  },
  {
    _rowIndex: 8, School: 'Michigan', Division: 'D1', Conference: 'Big Ten',
    'Academic Ranking': '#21', 'Acceptance Rate': '18%',
    'Head Coach': 'Hannah Nielsen', 'Coach Email': 'wlax@umich.edu',
    'Coach Phone': '', 'Coach Background': 'Former Tewaaraton Award winner at Northwestern',
    'Choate Connection': '', 'Roster Size': '33', 'Goalies on Roster': '3',
    'Graduating Goalies': '1 (2028)', 'Program URL': 'https://mgoblue.com/sports/womens-lacrosse',
    'Questionnaire URL': '', Priority: 'Target', Notes: 'August camp on watchlist',
    'Last Updated': '2026-03-29',
  },
  {
    _rowIndex: 9, School: 'Middlebury', Division: 'D3', Conference: 'NESCAC',
    'Academic Ranking': '#9 LAC', 'Acceptance Rate': '13%',
    'Head Coach': 'Kate Westhoff', 'Coach Email': 'wlax@middlebury.edu',
    'Coach Phone': '', 'Coach Background': '',
    'Choate Connection': 'NESCAC schools recruit heavily from NE prep',
    'Roster Size': '28', 'Goalies on Roster': '3', 'Graduating Goalies': '1 (2027)',
    'Program URL': 'https://athletics.middlebury.edu/sports/womens-lacrosse',
    'Questionnaire URL': '', Priority: 'Target',
    Notes: 'Perennial D3 power, top academics', 'Last Updated': '2026-03-29',
  },
  {
    _rowIndex: 10, School: 'Tufts', Division: 'D3', Conference: 'NESCAC',
    'Academic Ranking': '#32', 'Acceptance Rate': '10%',
    'Head Coach': 'Courtney Shea', 'Coach Email': 'wlax@tufts.edu',
    'Coach Phone': '', 'Coach Background': '',
    'Choate Connection': '', 'Roster Size': '26', 'Goalies on Roster': '2',
    'Graduating Goalies': '0', 'Program URL': 'https://gotuftsjumbos.com/sports/womens-lacrosse',
    'Questionnaire URL': '', Priority: 'Target', Notes: 'Near Boston',
    'Last Updated': '2026-03-29',
  },
];

export const DEMO_HOCKEY_PROGRAMS: Program[] = [
  {
    _rowIndex: 2, School: 'Wisconsin', Division: 'D1', Conference: 'WCHA',
    'Academic Ranking': '#42', 'Acceptance Rate': '49%',
    'Head Coach': 'Mark Johnson', 'Coach Email': 'whockey@wisc.edu',
    'Coach Phone': '', 'Coach Background': '1980 Miracle on Ice team member',
    'Choate Connection': '', 'Roster Size': '28', 'Defenders on Roster': '8',
    'Graduating Defenders': '2 (2027)', 'Program URL': 'https://uwbadgers.com/sports/womens-ice-hockey',
    'Questionnaire URL': '', Priority: 'Dream', Notes: 'Dominant program',
    'Last Updated': '2026-03-29',
  },
  {
    _rowIndex: 3, School: 'Northeastern', Division: 'D1', Conference: 'Hockey East',
    'Academic Ranking': '#53', 'Acceptance Rate': '7%',
    'Head Coach': 'Dave Flint', 'Coach Email': 'whockey@northeastern.edu',
    'Coach Phone': '', 'Coach Background': '',
    'Choate Connection': '', 'Roster Size': '26', 'Defenders on Roster': '7',
    'Graduating Defenders': '2 (2028)', 'Program URL': 'https://nuhuskies.com/sports/womens-ice-hockey',
    'Questionnaire URL': '', Priority: 'Target', Notes: 'Boston location',
    'Last Updated': '2026-03-29',
  },
  {
    _rowIndex: 4, School: 'Yale', Division: 'D1', Conference: 'ECAC',
    'Academic Ranking': '#5', 'Acceptance Rate': '5%',
    'Head Coach': 'Mark Bolding', 'Coach Email': 'whockey@yale.edu',
    'Coach Phone': '', 'Coach Background': '',
    'Choate Connection': 'Strong Choate-Yale pipeline', 'Roster Size': '25',
    'Defenders on Roster': '7', 'Graduating Defenders': '1 (2028)',
    'Program URL': 'https://yalebulldogs.com/sports/womens-ice-hockey',
    'Questionnaire URL': '', Priority: 'Dream', Notes: 'Close proximity to Choate, dual sport Ivy opportunity',
    'Last Updated': '2026-03-29',
  },
  {
    _rowIndex: 5, School: 'Harvard', Division: 'D1', Conference: 'ECAC',
    'Academic Ranking': '#3', 'Acceptance Rate': '3%',
    'Head Coach': 'Katey Stone', 'Coach Email': 'whockey@harvard.edu',
    'Coach Phone': '', 'Coach Background': 'Winningest coach in women\'s college hockey',
    'Choate Connection': 'Choate sends students to Harvard', 'Roster Size': '25',
    'Defenders on Roster': '8', 'Graduating Defenders': '2 (2027)',
    'Program URL': 'https://gocrimson.com/sports/womens-ice-hockey',
    'Questionnaire URL': '', Priority: 'Dream', Notes: '',
    'Last Updated': '2026-03-29',
  },
  {
    _rowIndex: 6, School: 'Middlebury', Division: 'D3', Conference: 'NESCAC',
    'Academic Ranking': '#9 LAC', 'Acceptance Rate': '13%',
    'Head Coach': 'Bill Mandigo', 'Coach Email': 'whockey@middlebury.edu',
    'Coach Phone': '', 'Coach Background': '',
    'Choate Connection': 'NESCAC recruits from NE prep schools',
    'Roster Size': '24', 'Defenders on Roster': '7', 'Graduating Defenders': '1 (2028)',
    'Program URL': 'https://athletics.middlebury.edu/sports/womens-ice-hockey',
    'Questionnaire URL': '', Priority: 'Target', Notes: 'Could do dual sport here in D3',
    'Last Updated': '2026-03-29',
  },
  {
    _rowIndex: 7, School: 'Brown', Division: 'D1', Conference: 'ECAC',
    'Academic Ranking': '#13', 'Acceptance Rate': '5%',
    'Head Coach': 'Syd Arbour', 'Coach Email': 'whockey@brown.edu',
    'Coach Phone': '', 'Coach Background': '',
    'Choate Connection': 'Ivy pipeline from Choate', 'Roster Size': '25',
    'Defenders on Roster': '7', 'Graduating Defenders': '1 (2028)',
    'Program URL': 'https://brownbears.com/sports/womens-ice-hockey',
    'Questionnaire URL': '', Priority: 'Target', Notes: '',
    'Last Updated': '2026-03-29',
  },
];

export const DEMO_COACHES: Coach[] = [
  {
    _rowIndex: 2, Name: 'Kelly Amonte Hiller', School: 'Northwestern', Sport: 'Lacrosse',
    Role: 'Head Coach', Email: 'lacrosse@northwestern.edu', Phone: '',
    'Alma Mater': 'Maryland', 'Years at Program': '23',
    Background: '7x NCAA champion coach, former US National Team',
    'Choate Connection': '', Notes: '', 'Last Updated': '2026-03-29',
  },
  {
    _rowIndex: 3, Name: 'Erica LaGrow', School: 'Yale', Sport: 'Lacrosse',
    Role: 'Head Coach', Email: 'wlax@yale.edu', Phone: '',
    'Alma Mater': '', 'Years at Program': '',
    Background: '',
    'Choate Connection': 'Yale has strong Choate pipeline', Notes: '', 'Last Updated': '2026-03-29',
  },
  {
    _rowIndex: 4, Name: 'Mark Bolding', School: 'Yale', Sport: 'Hockey',
    Role: 'Head Coach', Email: 'whockey@yale.edu', Phone: '',
    'Alma Mater': '', 'Years at Program': '',
    Background: '',
    'Choate Connection': 'Yale has strong Choate pipeline', Notes: '', 'Last Updated': '2026-03-29',
  },
  {
    _rowIndex: 5, Name: 'Hannah Nielsen', School: 'Michigan', Sport: 'Lacrosse',
    Role: 'Head Coach', Email: 'wlax@umich.edu', Phone: '',
    'Alma Mater': 'Northwestern', 'Years at Program': '5',
    Background: 'Former Tewaaraton Award winner, led Michigan to rapid rise',
    'Choate Connection': '', Notes: 'Runs summer camps at Michigan', 'Last Updated': '2026-03-29',
  },
  {
    _rowIndex: 6, Name: 'Katey Stone', School: 'Harvard', Sport: 'Hockey',
    Role: 'Head Coach', Email: 'whockey@harvard.edu', Phone: '',
    'Alma Mater': '', 'Years at Program': '28',
    Background: 'Winningest coach in women\'s college hockey history',
    'Choate Connection': 'Choate sends students to Harvard', Notes: '', 'Last Updated': '2026-03-29',
  },
  {
    _rowIndex: 7, Name: 'Syd Arbour', School: 'Brown', Sport: 'Hockey',
    Role: 'Head Coach', Email: 'whockey@brown.edu', Phone: '',
    'Alma Mater': '', 'Years at Program': '',
    Background: '',
    'Choate Connection': 'Ivy pipeline from Choate', Notes: '', 'Last Updated': '2026-03-29',
  },
];

// Real events from Matthew's Google Sheet "2025/2026 Lax Clinics/Showcases"
export const DEMO_EVENTS: CalendarEvent[] = [
  // ---- PAST EVENTS (completed) ----
  {
    _rowIndex: 2, 'Event Name': 'Peak Goalie Training', Sport: 'Lacrosse',
    Date: '2026-01-25', 'End Date': '2026-01-25', Location: 'Springfield College',
    Type: 'Camp', 'Coaches Attending': '', Cost: '$200',
    'Registration URL': '', 'Registration Deadline': '',
    Status: 'Attended', Notes: 'Sponsor: Peakgoalie/MYLA. 9am-12pm.',
  },
  {
    _rowIndex: 3, 'Event Name': 'BC Clinix', Sport: 'Lacrosse',
    Date: '2026-01-11', 'End Date': '2026-01-11', Location: 'Boston College',
    Type: 'Camp', 'Coaches Attending': 'BC coaching staff', Cost: '',
    'Registration URL': '', 'Registration Deadline': '',
    Status: 'Attended', Notes: '9am-3pm.',
  },
  {
    _rowIndex: 4, 'Event Name': 'Prep Showcase', Sport: 'Lacrosse',
    Date: '2026-01-18', 'End Date': '2026-01-18', Location: 'Bryant University, RI',
    Type: 'Showcase', 'Coaches Attending': '', Cost: '',
    'Registration URL': '', 'Registration Deadline': '',
    Status: 'Attended', Notes: 'Sponsor: ApexgirlsLaxevents. Hockey conflict — application process.',
  },
  {
    _rowIndex: 5, 'Event Name': 'Trinity Clinic', Sport: 'Lacrosse',
    Date: '2025-03-15', 'End Date': '2025-03-15', Location: 'Trinity College, CT',
    Type: 'Camp', 'Coaches Attending': 'Trinity coaching staff', Cost: '$50',
    'Registration URL': '', 'Registration Deadline': '',
    Status: 'Attended', Notes: '',
  },
  // ---- UPCOMING EVENTS ----
  {
    _rowIndex: 6, 'Event Name': 'American Select Tryouts Northeast', Sport: 'Lacrosse',
    Date: '2026-04-12', 'End Date': '2026-04-12', Location: 'UNH (University of New Hampshire)',
    Type: 'Tryout', 'Coaches Attending': '', Cost: '$100',
    'Registration URL': 'https://www.americanselect.com/',
    'Registration Deadline': '',
    Status: 'Registered', Notes: '10am-12pm. Tryout format.',
  },
  {
    _rowIndex: 7, 'Event Name': 'American Select Tryouts MASS', Sport: 'Lacrosse',
    Date: '2026-04-26', 'End Date': '2026-04-26', Location: 'Massachusetts',
    Type: 'Tryout', 'Coaches Attending': '', Cost: '$100',
    'Registration URL': 'https://www.americanselect.com/',
    'Registration Deadline': '',
    Status: 'Registered', Notes: '9am-12pm.',
  },
  {
    _rowIndex: 8, 'Event Name': 'All American Tryouts (New Balance)', Sport: 'Lacrosse',
    Date: '2026-05-03', 'End Date': '2026-05-03', Location: 'Union Point, MA',
    Type: 'Tryout', 'Coaches Attending': '', Cost: '$170',
    'Registration URL': '',
    'Registration Deadline': '',
    Status: 'Interested', Notes: 'Not yet registered. Tryout format.',
  },
  {
    _rowIndex: 9, 'Event Name': 'Champions Cup', Sport: 'Lacrosse',
    Date: '2026-06-20', 'End Date': '2026-06-21', Location: 'Boyds, MD',
    Type: 'Tournament', 'Coaches Attending': 'Multiple D1 coaches expected', Cost: '',
    'Registration URL': '',
    'Registration Deadline': '',
    Status: 'Registered', Notes: 'Sponsor: NH29 Purple. 748 miles, 2 overnights.',
  },
  {
    _rowIndex: 10, 'Event Name': 'NE Showcase', Sport: 'Lacrosse',
    Date: '2026-06-14', 'End Date': '2026-06-14', Location: 'Albany, NY',
    Type: 'Showcase', 'Coaches Attending': '', Cost: '',
    'Registration URL': '',
    'Registration Deadline': '',
    Status: 'Registered', Notes: 'Sponsor: NH29 Purple. 182 miles.',
  },
  {
    _rowIndex: 11, 'Event Name': 'NE Cup', Sport: 'Lacrosse',
    Date: '2026-06-26', 'End Date': '2026-06-28', Location: 'Amherst, MA',
    Type: 'Tournament', 'Coaches Attending': '', Cost: '',
    'Registration URL': '',
    'Registration Deadline': '',
    Status: 'Registered', Notes: 'Sponsor: NH29Purple. 192 miles.',
  },
  {
    _rowIndex: 12, 'Event Name': 'Top Threat', Sport: 'Lacrosse',
    Date: '2026-07-10', 'End Date': '2026-07-12', Location: 'Basking Ridge, NJ',
    Type: 'Tournament', 'Coaches Attending': '', Cost: '',
    'Registration URL': '',
    'Registration Deadline': '',
    Status: 'Registered', Notes: 'Sponsor: NH29Purple. 348 miles, 3 overnights, 4 food days.',
  },
  {
    _rowIndex: 13, 'Event Name': 'Mid-Atlantic', Sport: 'Lacrosse',
    Date: '2026-07-17', 'End Date': '2026-07-19', Location: 'MD State Fairgrounds',
    Type: 'Tournament', 'Coaches Attending': '', Cost: '',
    'Registration URL': '',
    'Registration Deadline': '',
    Status: 'Registered', Notes: 'Sponsor: NH29Purple. 652 miles, 3 overnights, 4 food days.',
  },
  {
    _rowIndex: 14, 'Event Name': 'American Selects', Sport: 'Lacrosse',
    Date: '2026-07-24', 'End Date': '2026-07-26', Location: 'Delaware',
    Type: 'Tournament', 'Coaches Attending': '', Cost: '',
    'Registration URL': 'https://www.americanselect.com/',
    'Registration Deadline': '',
    Status: 'TBD', Notes: 'Registration TBD.',
  },
  {
    _rowIndex: 15, 'Event Name': 'All-America Tourney', Sport: 'Lacrosse',
    Date: '2026-07-24', 'End Date': '2026-07-26', Location: 'Maryland',
    Type: 'Tournament', 'Coaches Attending': '', Cost: '',
    'Registration URL': '',
    'Registration Deadline': '',
    Status: 'Interested', Notes: 'Not registered.',
  },
  {
    _rowIndex: 16, 'Event Name': 'Lake Placid', Sport: 'Lacrosse',
    Date: '2026-07-26', 'End Date': '2026-07-29', Location: 'Lake Placid, NY',
    Type: 'Tournament', 'Coaches Attending': '', Cost: '',
    'Registration URL': '',
    'Registration Deadline': '',
    Status: 'Registered', Notes: 'Sponsor: Daughter\'s Nation. 454 miles, 4 overnights, 5 food days.',
  },
  {
    _rowIndex: 17, 'Event Name': 'Northeast Elite Recruiting Showcase', Sport: 'Lacrosse',
    Date: '2026-12-01', 'End Date': '2026-12-01', Location: 'Northeast (TBD)',
    Type: 'Showcase', 'Coaches Attending': '', Cost: '',
    'Registration URL': '',
    'Registration Deadline': '',
    Status: 'TBD', Notes: 'December 2026 — exact date TBD.',
  },
  // ---- HOCKEY EVENTS (details TBD) ----
  {
    _rowIndex: 18, 'Event Name': 'Harvard Hockey Camp', Sport: 'Hockey',
    Date: '2026-07-01', 'End Date': '2026-07-01', Location: 'Harvard University',
    Type: 'Camp', 'Coaches Attending': 'Harvard coaching staff', Cost: '',
    'Registration URL': 'https://gocrimson.com/sports/womens-ice-hockey',
    'Registration Deadline': '',
    Status: 'Interested', Notes: 'Date TBD — check for 2026 camp posting.',
  },
  {
    _rowIndex: 19, 'Event Name': 'Middlebury Hockey Camp', Sport: 'Hockey',
    Date: '2026-07-01', 'End Date': '2026-07-01', Location: 'Middlebury College',
    Type: 'Camp', 'Coaches Attending': 'Middlebury coaching staff', Cost: '',
    'Registration URL': 'https://athletics.middlebury.edu/sports/womens-ice-hockey',
    'Registration Deadline': '',
    Status: 'Interested', Notes: 'Date TBD — check for 2026 camp posting.',
  },
  {
    _rowIndex: 20, 'Event Name': 'Brown Hockey Camp', Sport: 'Hockey',
    Date: '2026-07-01', 'End Date': '2026-07-01', Location: 'Brown University',
    Type: 'Camp', 'Coaches Attending': 'Brown coaching staff', Cost: '',
    'Registration URL': 'https://brownbears.com/sports/womens-ice-hockey',
    'Registration Deadline': '',
    Status: 'Interested', Notes: 'Date TBD — check for 2026 camp posting.',
  },
];

export const DEMO_CONTACT_LOG: ContactLogEntry[] = [];

export const DEMO_TIMELINE: TimelineEvent[] = [
  { _rowIndex: 2, Date: '2026-03-29', Event: 'Recruiting dashboard launched', Category: 'Milestone', Sport: 'Both', Notes: '', Completed: 'true' },
  { _rowIndex: 3, Date: '2026-04-01', Event: 'Begin filling out recruiting questionnaires', Category: 'Task', Sport: 'Both', Notes: 'Start with top 10 targets', Completed: '' },
  { _rowIndex: 4, Date: '2026-04-12', Event: 'American Select Tryouts NE @ UNH', Category: 'Task', Sport: 'Lacrosse', Notes: '', Completed: '' },
  { _rowIndex: 5, Date: '2026-04-26', Event: 'American Select Tryouts MASS', Category: 'Task', Sport: 'Lacrosse', Notes: '', Completed: '' },
  { _rowIndex: 6, Date: '2026-06-01', Event: 'Update highlight reel — spring lacrosse season', Category: 'Task', Sport: 'Lacrosse', Notes: '', Completed: '' },
  { _rowIndex: 7, Date: '2026-06-14', Event: 'NE Showcase — Albany', Category: 'Task', Sport: 'Lacrosse', Notes: 'NH29 Purple', Completed: '' },
  { _rowIndex: 8, Date: '2026-06-20', Event: 'Champions Cup — Boyds MD', Category: 'Task', Sport: 'Lacrosse', Notes: 'NH29 Purple, 2 overnights', Completed: '' },
  { _rowIndex: 9, Date: '2026-07-10', Event: 'Top Threat — Basking Ridge NJ', Category: 'Task', Sport: 'Lacrosse', Notes: 'NH29 Purple, 3 overnights', Completed: '' },
  { _rowIndex: 10, Date: '2026-07-17', Event: 'Mid-Atlantic — MD State Fairgrounds', Category: 'Task', Sport: 'Lacrosse', Notes: 'NH29 Purple, 3 overnights', Completed: '' },
  { _rowIndex: 11, Date: '2026-07-26', Event: 'Lake Placid Tournament', Category: 'Task', Sport: 'Lacrosse', Notes: 'Daughter\'s Nation, 4 overnights', Completed: '' },
  { _rowIndex: 12, Date: '2026-09-01', Event: 'Sophomore year begins (4th form)', Category: 'Milestone', Sport: 'Both', Notes: '', Completed: '' },
  { _rowIndex: 13, Date: '2026-12-01', Event: 'Northeast Elite Recruiting Showcase', Category: 'Task', Sport: 'Lacrosse', Notes: 'Date TBD', Completed: '' },
  { _rowIndex: 14, Date: '2027-06-15', Event: 'NCAA D1 contact period opens (after soph year)', Category: 'NCAA', Sport: 'Both', Notes: 'Coaches can call/text after this date', Completed: '' },
  { _rowIndex: 15, Date: '2027-09-01', Event: 'Junior year — prime recruiting window', Category: 'Milestone', Sport: 'Both', Notes: 'Unofficial visits, coach conversations', Completed: '' },
  { _rowIndex: 16, Date: '2028-06-01', Event: 'Target for verbal commitment decisions', Category: 'Milestone', Sport: 'Both', Notes: '', Completed: '' },
  { _rowIndex: 17, Date: '2028-11-01', Event: 'Early Decision/Action applications due', Category: 'Academic', Sport: 'Both', Notes: '', Completed: '' },
  { _rowIndex: 18, Date: '2029-02-01', Event: 'NLI signing day (D1)', Category: 'NCAA', Sport: 'Both', Notes: '', Completed: '' },
];
